name: CI

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin

    - name: Build the release artifacts
      run: |
        set -x
        unset ANDROID_SDK_ROOT
        cd buildscripts
        ./download.sh > /dev/null
        ./buildall.sh --arch x86 mpv
        ./buildall.sh --arch x86_64 mpv
        ./buildall.sh --arch arm64 mpv
        ./buildall.sh
      env:
        GRADLE_OPTS: -Xmx4G
    - name: Get tag name
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        set -x
        echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Copy build artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        set -e
        mv app/build/outputs/aar/app-default-release.aar aniyomi-mpv-lib-${{ env.VERSION_TAG }}.aar
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION_TAG }}
        name: aniyomi-mpv-lib ${{ env.VERSION_TAG }}
        body: |
          library version ${{ env.VERSION_TAG }}
        files: |
          aniyomi-mpv-lib-${{ env.VERSION_TAG }}.aar
        draft: false
        prerelease: false
