name: build

on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [ armv7l, arm64, x86, x86_64 ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Export env vars
        run: buildscripts/include/ci.sh export >>$GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: gh-cache/
          key: "prefix-${{ hashFiles('buildscripts/**.sh') }}"
          restore-keys: "prefix-"
          enableCrossOsArchive: true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install autoconf pkg-config libtool ninja-build python3-pip
          sudo pip3 install meson

      - name: Download deps
        run: |
          mkdir -p "$CACHE_FOLDER"
          buildscripts/include/ci.sh install
        env:
          CACHE_MODE: "folder"
          CACHE_FOLDER: "${{ github.workspace }}/gh-cache"

      - name: Build the release artifacts
        run: |
          set -x
          unset ANDROID_SDK_ROOT
          cd buildscripts
          ./download.sh > /dev/null
          ./buildall.sh --arch ${{ matrix.architecture }} mpv
          ./buildall.sh -n

      - uses: actions/upload-artifact@v4
        with:
          name: mpv-lib-${{ matrix.architecture }}
          path: app/build/outputs/aar/app-release.aar