name: CI

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        architecture: [armv7l, arm64, x86, x86_64]

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    - uses: actions/cache@v4
      with:
        path: gh-cache/
        key: "prefix-${{ hashFiles('buildscripts/**.sh') }}"
        restore-keys: "prefix-"
        enableCrossOsArchive: true

    - name: Build the release artifacts
      run: |
        set -x
        unset ANDROID_SDK_ROOT
        cd buildscripts
        ./download.sh > /dev/null
        ./buildall.sh --arch ${{ matrix.architecture }} mpv
        ./buildall.sh -n

    - uses: actions/upload-artifact@v4
      with:
        name: aniyomi-mpv-lib-${{ matrix.architecture }}
        path: app/build/outputs/aar/app-default-release.aar
